name: Unit Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Unit Test
        run: npm run test:unit
